// Static content: the 9 dimensions, 36 questions, answer scale, and philosopher vectors.
// This is the file to edit when adding/editing quiz content.

export const sections = [
  { name: "Metaphysics", left: "Physicalist", right: "Non-Physicalist", color: "#2a3d5c",
    tooltip: "What is reality made of? Physicalists say everything is matter and energy. Non-physicalists believe something exists beyond the physical world." },
  { name: "Self", left: "Constructed", right: "Essential / Soul", color: "#2d5f3e",
    tooltip: "Is your identity built by your brain and experiences, or is there a core \"you\" (a soul, an essence) that exists independently?" },
  { name: "Epistemology", left: "Reason & Evidence", right: "Beyond Reason", color: "#c9981a",
    tooltip: "How do we know what’s true? One side trusts logic, science, and sensory evidence. The other believes some truths can only be accessed through intuition or experience beyond language." },
  { name: "Free Will", left: "Determinist", right: "Free Will", color: "#c4532e",
    tooltip: "Are your choices genuinely free, or are they the inevitable result of prior causes like your brain, genes, and upbringing?" },
  { name: "Meaning", left: "Self-Created", right: "Given / Cosmic", color: "#b07247",
    tooltip: "Is meaning something you build for yourself in an indifferent universe, or does it come from something larger like God, fate, or cosmic purpose?" },
  { name: "Moral Grounding", left: "Relativist", right: "Realist", color: "#6b7234",
    tooltip: "Is morality a human invention that varies across cultures, or are there moral truths that exist objectively, regardless of what anyone thinks?" },
  { name: "Normative Ethics", left: "Consequentialist", right: "Deontologist", color: "#6b3a6b",
    tooltip: "Should we judge actions by their outcomes (the ends justify the means), or by whether they follow the right rules and principles regardless of the result?" },
  { name: "Philosophy of Mind", left: "Materialist", right: "Consciousness Realist", color: "#8b3a4a",
    tooltip: "Is consciousness just neurons firing, fully explainable by science? Or is there something about subjective experience that goes beyond what any brain scan could capture?" },
  { name: "Existential Orientation", left: "Life Affirmer", right: "Pessimist", color: "#4a6670",
    tooltip: "On the whole, is existence something to embrace and be grateful for, or is suffering so central to life that optimism is mostly denial?" }
];

// s = section index (0-8), d = direction (+1 agreeing pushes toward section.right, -1 toward section.left)
export const questions = [
  { s: 0, t: "I believe in the supernatural (telekinesis, ghosts, magic).", d: 1 },
  { s: 0, t: "Science will explain nearly everything.", d: -1 },
  { s: 0, t: "Everything is made of atoms and can be explained by evolution, chemistry, and biology.", d: -1 },
  { s: 0, t: "Reality includes more than just matter and energy.", d: 1 },
  { s: 1, t: "I have a soul.", d: 1 },
  { s: 1, t: "I am the same person I was as a child.", d: 1 },
  { s: 1, t: "The “I” that feels like me is something the brain creates.", d: -1 },
  { s: 1, t: "I can’t exist without my brain.", d: -1 },
  { s: 2, t: "1 + 1 = 2 is the highest form of truth.", d: -1 },
  { s: 2, t: "I can trust my senses to figure out what’s true.", d: -1 },
  { s: 2, t: "I’ve had experiences I couldn’t justify with logic or evidence, but still trust as true.", d: 1 },
  { s: 2, t: "Some truths are beyond logical reasoning and language.", d: 1 },
  { s: 3, t: "I could have made different choices in my past.", d: 1 },
  { s: 3, t: "People’s choices are mostly products of their upbringing and environment.", d: -1 },
  { s: 3, t: "If you rewound time to the exact same moment, I’d make the same choice every time.", d: -1 },
  { s: 3, t: "When I make a hard decision, I feel like I could genuinely have gone either way, right up until I chose.", d: 1 },
  { s: 4, t: "Life has an inherent meaning that I didn’t create.", d: 1 },
  { s: 4, t: "Without God or some higher purpose, nothing ultimately matters.", d: 1 },
  { s: 4, t: "Death makes life more meaningful, not less.", d: -1 },
  { s: 4, t: "Struggle and suffering are necessary for a meaningful life.", d: -1 },
  { s: 5, t: "Some things are wrong regardless of culture or opinion.", d: 1 },
  { s: 5, t: "Morality is invented by humans.", d: -1 },
  { s: 5, t: "An action can be wrong even if nobody is harmed.", d: 1 },
  { s: 5, t: "What’s morally right varies by culture, with no culture more correct than another.", d: -1 },
  { s: 6, t: "It’s acceptable to harm one person to save many.", d: -1 },
  { s: 6, t: "The ends justify the means.", d: -1 },
  { s: 6, t: "I have stronger obligations to my family than to strangers.", d: 1 },
  { s: 6, t: "Rules should never be broken, even for good reasons.", d: 1 },
  { s: 7, t: "A robot could never truly feel anything.", d: 1 },
  { s: 7, t: "After I die, nothing happens.", d: -1 },
  { s: 7, t: "There is something it feels like to be me that science can’t fully capture.", d: 1 },
  { s: 7, t: "Consciousness is just neurons firing — nothing more, nothing mysterious about it.", d: -1 },
  { s: 8, t: "I would choose my life again if I could.", d: -1 },
  { s: 8, t: "Suffering is mostly pointless.", d: 1 },
  { s: 8, t: "Most people are in denial about how meaningless life is.", d: 1 },
  { s: 8, t: "Existence itself is something to be grateful for.", d: -1 }
];

export const optionLabels = ["Strongly Agree", "Agree", "Disagree", "Strongly Disagree"];
export const optionValues = [2, 1, -1, -2];

// vec[i] is each philosopher's position on sections[i], from -1 (left pole) to 1 (right pole)
export const philosophers = [
  { name: "Friedrich Nietzsche", years: "1844–1900",
    vec: [-0.6, -0.8, -0.3, 0.4, -0.9, -0.7, -0.2, -0.1, -0.8],
    desc: "Rejected metaphysical foundations, the fixed self, and objective morality. Championed self-created meaning, the will to power, and amor fati. Believed consciousness had depths science hadn’t touched, but dismissed the supernatural." },
  { name: "Albert Camus", years: "1913–1960",
    vec: [-0.7, -0.6, -0.5, 0.3, -0.9, -0.4, -0.3, -0.5, -0.6],
    desc: "Confronted the absurd head-on: the universe is silent, meaning is self-made, and the only serious philosophical question is whether to go on living. Answered yes, with defiant joy." },
  { name: "Jean-Paul Sartre", years: "1905–1980",
    vec: [-0.7, -0.9, -0.4, 0.9, -0.8, -0.6, -0.1, -0.6, -0.3],
    desc: "Existence precedes essence. No human nature, no excuses, radical freedom and radical responsibility. The self is what you make through action. Meaning is chosen." },
  { name: "Søren Kierkegaard", years: "1813–1855",
    vec: [0.5, 0.7, 0.7, 0.8, 0.7, 0.6, 0.6, 0.7, -0.4],
    desc: "The father of existentialism paradoxically grounded meaning in a leap of faith. Subjective truth over objective, the self before God, passion over proof. Saw anxiety as the dizziness of freedom." },
  { name: "David Hume", years: "1711–1776",
    vec: [-0.8, -0.9, -0.7, -0.6, -0.4, -0.7, -0.5, -0.6, -0.2],
    desc: "The great skeptic. Denied causation as anything more than habit, dissolved the self into a bundle of perceptions, and argued morality comes from sentiment, not reason." },
  { name: "Immanuel Kant", years: "1724–1804",
    vec: [0.2, 0.4, -0.3, 0.5, 0.3, 0.9, 0.9, 0.3, -0.3],
    desc: "Built the cathedral of duty ethics. Moral law is universal and discoverable through reason alone. Free will is necessary for morality, and some things lie beyond what science can reach." },
  { name: "John Stuart Mill", years: "1806–1873",
    vec: [-0.5, -0.3, -0.6, 0.3, -0.4, -0.4, -0.9, -0.3, -0.3],
    desc: "The great utilitarian. Consequences are what matter, and the best action produces the most happiness for the most people. Believed reason and evidence should guide both ethics and politics." },
  { name: "René Descartes", years: "1596–1650",
    vec: [0.1, 0.8, -0.4, 0.6, 0.5, 0.7, 0.5, 0.9, -0.3],
    desc: "I think, therefore I am. Radical doubt led to the one thing he couldn’t doubt: the thinking self. Strong dualist who saw mind and body as distinct substances." },
  { name: "Arthur Schopenhauer", years: "1788–1860",
    vec: [0.3, -0.4, 0.4, -0.7, 0.2, 0.2, -0.1, 0.6, 0.9],
    desc: "The philosopher of pessimism. The world is driven by blind Will, desire is endless, satisfaction is fleeting. Found solace only in art, compassion, and ascetic renunciation." },
  { name: "Simone de Beauvoir", years: "1908–1986",
    vec: [-0.6, -0.7, -0.4, 0.7, -0.7, -0.3, -0.2, -0.4, -0.5],
    desc: "Extended existential freedom into ethics and gender. The self is not born but made. Freedom must be actively claimed against systems of oppression." },
  { name: "Epicurus", years: "341–270 BCE",
    vec: [-0.9, -0.5, -0.6, -0.2, -0.5, -0.5, -0.6, -0.8, -0.7],
    desc: "Materialist, atomist, refined hedonist. Death is nothing to us. Pleasure, understood as the absence of pain, is the highest good. Simple living, close friendships, philosophical conversation." },
  { name: "Marcus Aurelius", years: "121–180 CE",
    vec: [0.1, -0.2, -0.4, 0.1, -0.6, 0.5, 0.3, 0.1, -0.9],
    desc: "Stoic emperor. Focus only on what you can control. Virtue is the sole good, externals are indifferent. Accept fate with equanimity. Life is brief but sufficient." },
  { name: "The Buddha", years: "c. 563–483 BCE",
    vec: [0.2, -1.0, 0.3, 0.0, -0.5, 0.3, -0.1, 0.5, -0.5],
    desc: "The self is an illusion. Suffering arises from craving and attachment. Liberation comes through direct insight, not belief. Consciousness is luminous and knowing." },
  { name: "Thomas Nagel", years: "1937–",
    vec: [0.4, 0.2, -0.2, 0.3, 0.1, 0.6, 0.3, 0.9, -0.1],
    desc: "Asked what it’s like to be a bat and changed philosophy of mind. Consciousness is irreducible to physical processes. Deeply skeptical that materialism can explain subjective experience." }
];
